apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-public-traffic
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: public
  policyTypes:
  - Ingress
  ingress:
  - from: []
    ports:
    - protocol: TCP
      port: 5001