apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
    network: internal
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
    network: internal
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    monitoring: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    argocd: enabled